name: Sync files
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.3.0

      - name: Sync files across repositories
        uses: webitel/reusable-workflows/actions/file-sync@file-sync-v1.0.2
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          IS_FINE_GRAINED: true
          CONFIG_PATH: golang/sync.yml
          ASSIGNEES: kirychukyurii
          COMMIT_EACH_FILE: true
          OVERWRITE_EXISTING_PR: true
          DRY_RUN: false
          NUNJUCKS_VARIABLE_START: "((("
          NUNJUCKS_VARIABLE_END: ")))"

