name: Sync Golang

on:
  push:
    branches: [ main ]
    paths:
      - common/**
      - golang/**
      - .github/workflows/sync-golang.yml
      - .github/workflows/sync-reusable.yml

  workflow_dispatch:

concurrency:
  group: sync-golang-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync
    strategy:
      fail-fast: false
      matrix:
        include:
          - config-path: golang/sync.yml
            sync-type: dynamic

          - config-path: golang/sync-static.yml
            sync-type: static

    uses: ./.github/workflows/sync-reusable.yml
    secrets: inherit
    with:
      config-path: ${{ matrix.config-path }}
      sync-type: ${{ matrix.sync-type }}
      repositories: |
        call_audit
        call_center
        cases
        chat_manager
        engine
        flow_manager
        im-account-service
        im-contact-service
        im-delivery-service
        im-gateway-service
        im-providers-service
        im-thread-service
        logger
        media-exporter
        storage
        webitel-fts
        webitel-wfm
        webitel.go
        webrtc_recorder
        web-meeting-backend
