name: Sync files
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.3.0

      - name: Sync files across repositories
        uses: webitel/reusable-workflows/actions/file-sync-action@097c26a53ad445517ac74b73c0bc9af97e5c0aad
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          IS_FINE_GRAINED: true
          CONFIG_PATH: golang/sync.yml
          ASSIGNEES: kirychukyurii
          COMMIT_EACH_FILE: true
          OVERWRITE_EXISTING_PR: true
          DRY_RUN: false